### PR TITLE
NONE: Run make generate to update deployinator

### PR DESCRIPTION
**Pull request by fcobb**
**Status:** Ready
**What/Why:**
- I ran 'make generate' on master and these were the results.
- Should we commit these changes?

### CODE REVIEW

**Comment by Burr** [comment]
Looks like the build fails due to the deleted BUILD.bazel file, replication needs it?

**Comment by smecsia** [comment]
The deleted BUILD.bazel file doesn't seem to be related to the other changes.

**Comment by fcobb** [comment]
I reverted the deletion of `pkg/util/sets/BUILD.bazel`

**Comment by ash2k** [comment]
See https://github.com/atlassian/voyager/pull/69

**Comment by fcobb** [comment]
Closing as @ash2k has fixes in https://github.com/atlassian/voyager/pull/69/files.

**Pull request closed without merging**
